export type TushareStatement = 'income' | 'balance' | 'cash_flow';

export interface TushareFinancialFieldMapItem {
  label: string;
  field: string | null;
  note?: string;
}

export const tushareIncomeFieldMap: TushareFinancialFieldMapItem[] = [
  { label: '报告期', field: 'report_name' },
  { label: '报告日期', field: 'report_date' },
  { label: '公告日期', field: 'ann_date' },
  { label: '营业总收入', field: 'total_revenue' },
  { label: '其中：营业收入', field: 'revenue' },
  { label: '营业总成本', field: 'total_cogs' },
  { label: '其中：营业成本', field: 'oper_cost' },
  { label: '营业税金及附加', field: 'biz_tax_surchg' },
  { label: '销售费用', field: 'sell_exp' },
  { label: '管理费用', field: 'admin_exp' },
  { label: '研发费用', field: 'rd_exp' },
  { label: '财务费用', field: 'fin_exp' },
  { label: '其中：利息费用', field: 'fin_exp_int_exp' },
  { label: '利息收入', field: 'fin_exp_int_inc' },
  { label: '资产减值损失', field: 'assets_impair_loss' },
  { label: '信用减值损失', field: 'credit_impa_loss' },
  { label: '公允价值变动收益', field: 'fv_value_chg_gain' },
  { label: '投资收益', field: 'invest_income' },
  { label: '其中：对联营企业和合营企业的投资收益', field: 'ass_invest_income' },
  { label: '资产处置收益', field: 'nca_disploss' },
  { label: '营业利润', field: 'operate_profit' },
  { label: '营业外收入', field: 'non_oper_income' },
  { label: '营业外支出', field: 'non_oper_exp' },
  { label: '利润总额', field: 'total_profit' },
  { label: '所得税费用', field: 'income_tax' },
  { label: '净利润', field: 'n_income' },
  { label: '持续经营净利润', field: 'continued_net_profit' },
  { label: '归属于母公司股东的净利润', field: 'n_income_attr_p' },
  { label: '少数股东损益', field: 'minority_gain' },
  { label: '扣除非经常性损益后的净利润', field: 'profit_dedt', note: '来自 Tushare fina_indicator，与利润表同报告期合并展示' },
  { label: '基本每股收益', field: 'basic_eps' },
  { label: '稀释每股收益', field: 'diluted_eps' },
  { label: '其他综合收益', field: 'oth_compr_income' },
  { label: '综合收益总额', field: 't_compr_income' },
  { label: '归属于母公司股东的综合收益总额', field: 'compr_inc_attr_p' },
  { label: '归属于少数股东的综合收益总额', field: 'compr_inc_attr_m_s' },
];

export const tushareCashFlowFieldMap: TushareFinancialFieldMapItem[] = [
  { label: '报告期', field: 'report_name' },
  { label: '报告日期', field: 'report_date' },
  { label: '公告日期', field: 'ann_date' },
  { label: '销售商品、提供劳务收到的现金', field: 'c_fr_sale_sg' },
  { label: '收到的税费返还', field: 'recp_tax_rends' },
  { label: '收到其他与经营活动有关的现金', field: 'c_fr_oth_operate_a' },
  { label: '经营活动现金流入小计', field: 'c_inf_fr_operate_a' },
  { label: '购买商品、接受劳务支付的现金', field: 'c_paid_goods_s' },
  { label: '支付给职工以及为职工支付的现金', field: 'c_paid_to_for_empl' },
  { label: '支付的各项税费', field: 'c_paid_for_taxes' },
  { label: '支付其他与经营活动有关的现金', field: 'oth_cash_pay_oper_act' },
  { label: '经营活动现金流出小计', field: 'st_cash_out_act' },
  { label: '经营活动产生的现金流量净额', field: 'n_cashflow_act' },
  { label: '收回投资收到的现金', field: 'c_disp_withdrwl_invest' },
  { label: '取得投资收益收到的现金', field: 'c_recp_return_invest' },
  { label: '处置固定资产、无形资产和其他长期资产收回的现金净额', field: 'n_recp_disp_fiolta' },
  { label: '处置子公司及其他营业单位收到的现金净额', field: 'n_recp_disp_sobu' },
  { label: '投资活动现金流入小计', field: 'stot_inflows_inv_act' },
  { label: '购建固定资产、无形资产和其他长期资产支付的现金', field: 'c_pay_acq_const_fiolta' },
  { label: '投资支付的现金', field: 'c_paid_invest' },
  { label: '取得子公司及其他营业单位支付的现金净额', field: 'n_disp_subs_oth_biz' },
  { label: '投资活动现金流出小计', field: 'stot_out_inv_act' },
  { label: '投资活动产生的现金流量净额', field: 'n_cashflow_inv_act' },
  { label: '自由现金流', field: 'free_cashflow' },
  { label: '取得借款收到的现金', field: 'c_recp_borrow' },
  { label: '发行债券收到的现金', field: 'proc_issue_bonds' },
  { label: '筹资活动现金流入小计', field: 'stot_cash_in_fnc_act' },
  { label: '偿还债务支付的现金', field: 'c_prepay_amt_borr' },
  { label: '分配股利、利润或偿付利息支付的现金', field: 'c_pay_dist_dpcp_int_exp' },
  { label: '筹资活动现金流出小计', field: 'stot_cashout_fnc_act' },
  { label: '筹资活动产生的现金流量净额', field: 'n_cash_flows_fnc_act' },
  { label: '汇率变动对现金及现金等价物的影响', field: 'eff_fx_flu_cash' },
  { label: '现金及现金等价物净增加额', field: 'n_incr_cash_cash_equ' },
  { label: '加：期初现金及现金等价物余额', field: 'c_cash_equ_beg_period' },
  { label: '期末现金及现金等价物余额', field: 'c_cash_equ_end_period' },
];

export const tushareBalanceFieldMap: TushareFinancialFieldMapItem[] = [
  { label: '报告期', field: 'report_name' },
  { label: '报告日期', field: 'report_date' },
  { label: '公告日期', field: 'ann_date' },
  { label: '货币资金', field: 'money_cap' },
  { label: '交易性金融资产', field: 'trad_asset' },
  { label: '应收票据及应收账款', field: 'accounts_receiv_bill' },
  { label: '其中：应收票据', field: 'notes_receiv' },
  { label: '应收账款', field: 'accounts_receiv' },
  { label: '预付款项', field: 'prepayment' },
  { label: '应收利息', field: 'int_receiv' },
  { label: '应收股利', field: 'div_receiv' },
  { label: '其他应收款', field: 'oth_rcv_total' },
  { label: '存货', field: 'inventories' },
  { label: '合同资产', field: 'contract_assets' },
  { label: '一年内到期的非流动资产', field: 'nca_within_1y' },
  { label: '其他流动资产', field: 'oth_cur_assets' },
  { label: '流动资产合计', field: 'total_cur_assets' },
  { label: '长期股权投资', field: 'lt_eqt_invest' },
  { label: '其他权益工具投资', field: 'oth_eqt_tools' },
  { label: '其他非流动金融资产', field: 'oth_nca' },
  { label: '投资性房地产', field: 'invest_real_estate' },
  { label: '固定资产合计', field: 'fix_assets_total' },
  { label: '其中：固定资产', field: 'fix_assets' },
  { label: '在建工程合计', field: 'cip_total' },
  { label: '其中：在建工程', field: 'cip' },
  { label: '无形资产', field: 'intan_assets' },
  { label: '开发支出', field: 'r_and_d' },
  { label: '商誉', field: 'goodwill' },
  { label: '长期待摊费用', field: 'lt_amor_exp' },
  { label: '递延所得税资产', field: 'defer_tax_assets' },
  { label: '非流动资产合计', field: 'total_nca' },
  { label: '资产合计', field: 'total_assets' },
  { label: '短期借款', field: 'st_borr' },
  { label: '应付票据及应付账款', field: 'payables' },
  { label: '应付账款', field: 'accounts_pay' },
  { label: '合同负债', field: 'contract_liab' },
  { label: '应付职工薪酬', field: 'payroll_payable' },
  { label: '应交税费', field: 'taxes_payable' },
  { label: '应付利息', field: 'int_payable' },
  { label: '应付股利', field: 'div_payable' },
  { label: '其他应付款', field: 'oth_pay_total' },
  { label: '一年内到期的非流动负债', field: 'non_cur_liab_due_1y' },
  { label: '其他流动负债', field: 'oth_cur_liab' },
  { label: '流动负债合计', field: 'total_cur_liab' },
  { label: '长期借款', field: 'lt_borr' },
  { label: '递延所得税负债', field: 'defer_tax_liab' },
  { label: '递延收益-非流动负债', field: 'defer_inc_non_cur_liab' },
  { label: '非流动负债合计', field: 'total_ncl' },
  { label: '负债合计', field: 'total_liab' },
  { label: '实收资本(或股本)', field: 'total_share' },
  { label: '资本公积', field: 'cap_rese' },
  { label: '减：库存股', field: 'treasury_share' },
  { label: '其他综合收益', field: 'oth_comp_income' },
  { label: '盈余公积', field: 'surplus_rese' },
  { label: '未分配利润', field: 'undistr_porfit' },
  { label: '归属于母公司股东权益合计', field: 'total_hldr_eqy_exc_min_int' },
  { label: '少数股东权益', field: 'minority_int' },
  { label: '股东权益合计', field: 'total_hldr_eqy_inc_min_int' },
  { label: '负债和股东权益总计', field: 'total_liab_hldr_eqy' },
];

export const tushareFinancialFieldMaps: Record<TushareStatement, TushareFinancialFieldMapItem[]> = {
  income: tushareIncomeFieldMap,
  balance: tushareBalanceFieldMap,
  cash_flow: tushareCashFlowFieldMap,
};