export type XueqiuStatement = 'income' | 'balance' | 'cash_flow';

export interface XueqiuFinancialFieldMapItem {
  label: string;
  field: string | null;
  note?: string;
}

export const xueqiuIncomeFieldMap: XueqiuFinancialFieldMapItem[] = [
  { label: '报告期', field: 'report_name' },
  { label: '报告日期', field: 'report_date' },
  { label: '营业总收入', field: 'total_revenue' },
  { label: '其中：营业收入', field: 'revenue' },
  { label: '营业总成本', field: 'operating_costs' },
  { label: '其中：营业成本', field: 'operating_cost' },
  { label: '营业税金及附加', field: 'operating_taxes_and_surcharge' },
  { label: '销售费用', field: 'sales_fee' },
  { label: '管理费用', field: 'manage_fee' },
  { label: '研发费用', field: 'rad_cost' },
  { label: '财务费用', field: 'financing_expenses' },
  { label: '其中：利息费用', field: 'finance_cost_interest_fee' },
  { label: '利息收入', field: 'finance_cost_interest_income' },
  { label: '资产减值损失', field: 'asset_impairment_loss' },
  { label: '信用减值损失', field: 'credit_impairment_loss' },
  { label: '公允价值变动收益', field: 'income_from_chg_in_fv' },
  { label: '投资收益', field: 'invest_income' },
  { label: '其中：对联营企业和合营企业的投资收益', field: null, note: '603288 样本为空，暂未确认稳定字段' },
  { label: '资产处置收益', field: 'asset_disposal_income' },
  { label: '其他收益', field: 'other_income' },
  { label: '营业利润', field: 'op' },
  { label: '营业外收入', field: 'non_operating_income' },
  { label: '其中：非流动资产处置利得', field: null, note: '603288 样本为空' },
  { label: '营业外支出', field: 'non_operating_payout' },
  { label: '其中：非流动资产处置损失', field: null, note: '603288 样本为空' },
  { label: '利润总额', field: 'profit_total_amt' },
  { label: '所得税费用', field: 'income_tax_expenses' },
  { label: '净利润差额(合计平衡项目)', field: null, note: '603288 样本为空' },
  { label: '净利润', field: 'net_profit' },
  { label: '持续经营净利润', field: 'continous_operating_np' },
  { label: '归属于母公司股东的净利润', field: 'net_profit_atsopc' },
  { label: '少数股东损益', field: 'minority_gal' },
  { label: '扣除非经常性损益后的净利润', field: 'net_profit_after_nrgal_atsolc' },
  { label: '基本每股收益', field: 'basic_eps' },
  { label: '稀释每股收益', field: 'dlt_earnings_per_share' },
  { label: '其他综合收益', field: 'othr_compre_income' },
  { label: '归属母公司所有者的其他综合收益', field: 'othr_compre_income_atoopc' },
  { label: '综合收益总额', field: 'total_compre_income' },
  { label: '归属于母公司股东的综合收益总额', field: 'total_compre_income_atsopc' },
  { label: '归属于少数股东的综合收益总额', field: 'total_compre_income_atms' },
];

export const xueqiuCashFlowFieldMap: XueqiuFinancialFieldMapItem[] = [
  { label: '报告期', field: 'report_name' },
  { label: '报告日期', field: 'report_date' },
  { label: '销售商品、提供劳务收到的现金', field: 'cash_received_of_sales_service' },
  { label: '收到的税费返还', field: 'refund_of_tax_and_levies' },
  { label: '收到其他与经营活动有关的现金', field: 'cash_received_of_othr_oa' },
  { label: '经营活动现金流入小计', field: 'sub_total_of_ci_from_oa' },
  { label: '购买商品、接受劳务支付的现金', field: 'goods_buy_and_service_cash_pay' },
  { label: '支付给职工以及为职工支付的现金', field: 'cash_paid_to_employee_etc' },
  { label: '支付的各项税费', field: 'payments_of_all_taxes' },
  { label: '支付其他与经营活动有关的现金', field: 'othrcash_paid_relating_to_oa' },
  { label: '经营活动现金流出小计', field: 'sub_total_of_cos_from_oa' },
  { label: '经营活动产生的现金流量净额', field: 'ncf_from_oa' },
  { label: '收回投资收到的现金', field: 'cash_received_of_dspsl_invest' },
  { label: '取得投资收益收到的现金', field: 'invest_income_cash_received' },
  { label: '处置固定资产、无形资产和其他长期资产收回的现金净额', field: 'net_cash_of_disposal_assets' },
  { label: '处置子公司及其他营业单位收到的现金净额', field: null, note: '603288 样本为空' },
  { label: '收到其他与投资活动有关的现金', field: 'cash_received_of_othr_ia' },
  { label: '投资活动现金流入小计', field: 'sub_total_of_ci_from_ia' },
  { label: '购建固定资产、无形资产和其他长期资产支付的现金', field: 'cash_paid_for_assets' },
  { label: '投资支付的现金', field: 'invest_paid_cash' },
  { label: '取得子公司及其他营业单位支付的现金净额', field: 'net_cash_amt_from_branch' },
  { label: '支付其他与投资活动有关的现金', field: null, note: '603288 样本为空' },
  { label: '投资活动现金流出小计', field: 'sub_total_of_cos_from_ia' },
  { label: '投资活动产生的现金流量净额', field: 'ncf_from_ia' },
  { label: '吸收投资收到的现金', field: 'cash_received_of_absorb_invest' },
  { label: '其中：子公司吸收少数股东投资收到的现金', field: null, note: '603288 样本为空' },
  { label: '取得借款收到的现金', field: 'cash_received_of_borrowing' },
  { label: '发行债券收到的现金', field: null, note: '603288 样本为空' },
  { label: '收到其他与筹资活动有关的现金', field: 'cash_received_of_othr_fa' },
  { label: '筹资活动现金流入小计', field: 'sub_total_of_ci_from_fa' },
  { label: '偿还债务支付的现金', field: 'cash_pay_for_debt' },
  { label: '分配股利、利润或偿付利息支付的现金', field: 'cash_paid_of_distribution' },
  { label: '其中：子公司支付给少数股东的股利', field: null, note: '603288 样本为空' },
  { label: '支付其他与筹资活动有关的现金', field: 'othrcash_paid_relating_to_fa' },
  { label: '筹资活动现金流出小计', field: 'sub_total_of_cos_from_fa' },
  { label: '筹资活动产生的现金流量净额', field: 'ncf_from_fa' },
  { label: '汇率变动对现金及现金等价物的影响', field: 'effect_of_exchange_chg_on_cce' },
  { label: '现金及现金等价物净增加额', field: 'net_increase_in_cce' },
  { label: '加：期初现金及现金等价物余额', field: 'initial_balance_of_cce' },
  { label: '期末现金及现金等价物余额', field: 'final_balance_of_cce' },
];

export const xueqiuBalanceFieldMap: XueqiuFinancialFieldMapItem[] = [
  { label: '报告期', field: 'report_name' },
  { label: '报告日期', field: 'report_date' },
  { label: '货币资金', field: 'currency_funds' },
  { label: '交易性金融资产', field: 'tradable_fnncl_assets' },
  { label: '应收票据及应收账款', field: 'ar_and_br' },
  { label: '其中：应收票据', field: 'bills_receivable' },
  { label: '应收账款', field: 'account_receivable' },
  { label: '预付款项', field: 'pre_payment' },
  { label: '应收利息', field: 'interest_receivable' },
  { label: '应收股利', field: null, note: '603288 样本为空' },
  { label: '其他应收款', field: 'othr_receivables' },
  { label: '存货', field: 'inventory' },
  { label: '合同资产', field: null, note: '603288 样本为空' },
  { label: '划分为持有待售的资产', field: null, note: '603288 样本为空' },
  { label: '一年内到期的非流动资产', field: null, note: '603288 样本为空' },
  { label: '其他流动资产', field: 'othr_current_assets' },
  { label: '流动资产合计', field: 'total_current_assets' },
  { label: '可供出售金融资产', field: null, note: '603288 样本为空' },
  { label: '持有至到期投资', field: null, note: '603288 样本为空' },
  { label: '长期应收款', field: null, note: '603288 样本为空' },
  { label: '长期股权投资', field: null, note: '603288 样本为空' },
  { label: '其他权益工具投资', field: null, note: '603288 样本为空' },
  { label: '其他非流动金融资产', field: 'other_illiquid_fnncl_assets' },
  { label: '投资性房地产', field: 'invest_property' },
  { label: '固定资产合计', field: 'fixed_asset_sum' },
  { label: '其中：固定资产', field: 'fixed_asset' },
  { label: '固定资产清理', field: null, note: '603288 样本为空' },
  { label: '在建工程合计', field: 'construction_in_process_sum' },
  { label: '其中：在建工程', field: 'construction_in_process' },
  { label: '工程物资', field: null, note: '603288 样本为空' },
  { label: '生产性生物资产', field: null, note: '603288 样本为空' },
  { label: '油气资产', field: null, note: '603288 样本为空' },
  { label: '无形资产', field: 'intangible_assets' },
  { label: '开发支出', field: null, note: '603288 样本为空' },
  { label: '商誉', field: 'goodwill' },
  { label: '长期待摊费用', field: 'lt_deferred_expense' },
  { label: '递延所得税资产', field: 'dt_assets' },
  { label: '其他非流动资产', field: 'othr_noncurrent_assets' },
  { label: '非流动资产合计', field: 'total_noncurrent_assets' },
  { label: '资产合计', field: 'total_assets' },
  { label: '短期借款', field: 'st_loan' },
  { label: '交易性金融负债', field: null, note: '603288 样本为空' },
  { label: '衍生金融负债', field: 'derivative_fnncl_liab' },
  { label: '应付票据及应付账款', field: 'bp_and_ap' },
  { label: '应付票据', field: 'bill_payable' },
  { label: '应付账款', field: 'accounts_payable' },
  { label: '预收款项', field: null, note: '603288 样本为空' },
  { label: '合同负债', field: 'contract_liabilities' },
  { label: '应付职工薪酬', field: 'payroll_payable' },
  { label: '应交税费', field: 'tax_payable' },
  { label: '应付利息', field: null, note: '603288 样本为空' },
  { label: '应付股利', field: 'dividend_payable' },
  { label: '其他应付款', field: 'othr_payables' },
  { label: '划分为持有待售的负债', field: null, note: '603288 样本为空' },
  { label: '一年内到期的非流动负债', field: 'noncurrent_liab_due_in1y' },
  { label: '其他流动负债', field: 'othr_current_liab' },
  { label: '流动负债合计', field: 'total_current_liab' },
  { label: '长期借款', field: 'lt_loan' },
  { label: '应付债券', field: null, note: '603288 样本为空' },
  { label: '长期应付款合计', field: 'lt_payable_sum' },
  { label: '长期应付款', field: null, note: '603288 样本为空' },
  { label: '专项应付款', field: null, note: '603288 样本为空' },
  { label: '预计负债', field: null, note: '603288 样本为空' },
  { label: '递延所得税负债', field: 'dt_liab' },
  { label: '递延收益-非流动负债', field: 'noncurrent_liab_di' },
  { label: '其他非流动负债', field: 'othr_non_current_liab' },
  { label: '非流动负债合计', field: 'total_noncurrent_liab' },
  { label: '负债合计', field: 'total_liab' },
  { label: '实收资本(或股本)', field: 'shares' },
  { label: '其他权益工具', field: null, note: '603288 样本为空' },
  { label: '其中：优先股', field: null, note: '603288 样本为空' },
  { label: '永续债', field: null, note: '603288 样本为空' },
  { label: '资本公积', field: 'capital_reserve' },
  { label: '减：库存股', field: 'treasury_stock' },
  { label: '其他综合收益', field: 'othr_compre_income' },
  { label: '专项储备', field: null, note: '603288 样本为空' },
  { label: '盈余公积', field: 'earned_surplus' },
  { label: '未分配利润', field: 'undstrbtd_profit' },
  { label: '一般风险准备', field: null, note: '603288 样本为空' },
  { label: '外币报表折算差额', field: null, note: '603288 样本为空' },
  { label: '归属于母公司股东权益合计', field: 'total_quity_atsopc' },
  { label: '少数股东权益', field: 'minority_equity' },
  { label: '股东权益合计', field: 'total_holders_equity' },
  { label: '负债和股东权益总计', field: 'total_liab_and_holders_equity' },
];

export const xueqiuFinancialFieldMaps: Record<XueqiuStatement, XueqiuFinancialFieldMapItem[]> = {
  income: xueqiuIncomeFieldMap,
  balance: xueqiuBalanceFieldMap,
  cash_flow: xueqiuCashFlowFieldMap,
};